//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Infra.Data.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHabitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tHabitacion()
        {
            this.tAlquiler = new HashSet<tAlquiler>();
        }
    
        public int IdHabitacion { get; set; }
        public Nullable<int> numeroCamas { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string fkTipo { get; set; }
        public string observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAlquiler> tAlquiler { get; set; }
        public virtual tTipo tTipo { get; set; }
    }
}
